### ISSUE TITLE
Cannot get Crypto.subtle object when using dart2js (or webserve --release)

### ISSUE THREAD

**Issue by edyu** [dint-dev/cryptography#21]
Ok, this is weird and I'm not sure why this happens but when I put --release to webserve which probably uses dart2js, I'm getting the following error when I use newKeyPair. The problem is that subtle object is not retrievable in the cryptography code.
There is not such error when I leave out --release. 
I was able to get window.crypto and window.crypto.subtle and window.isSecureContext is true so the object definitely exists. Not sure whether it's a fluke on the JS side or not. At first I thought maybe because I'm not using certificates when in development that secure context is false but I was able to verify when running ddc, isSecureContext is still true regardless of whether running in --release or not.
<pre>
stacktrace.dart:67 EXCEPTION: NoSuchMethodError: method not found: 'get$subtle' (J.getInterceptor$x(...).get$subtle is not a function)
STACKTRACE: 
TypeError: J.getInterceptor$x(...).get$subtle is not a function
    at Object.get$subtle$x (http://localhost:9000/main.dart.js:3729:43)
    at RsaPss.get$_webCryptoImplementation (http://localhost:9000/main.dart.js:33522:13)
    at RsaPss.newKeyPair$0 (http://localhost:9000/main.dart.js:33530:42)
    at http://localhost:9000/main.dart.js:37554:69
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:9000/main.dart.js:4035:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:9000/main.dart.js:16812:12)
    at Object._asyncStartSync (http://localhost:9000/main.dart.js:3999:20)
    at WebTrapdoor.genKeyPair$0 (http://localhost:9000/main.dart.js:37568:16)
    at http://localhost:9000/main.dart.js:37272:74
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:9000/main.dart.js:4035:15)
</pre>

**Comment by edyu** [comment]
I filed dart-lang/sdk#42194 in case it's not your error.

**Comment by edyu** [comment]
Looks like a platform bug. I also filed dart-lang/sdk#42144 which is related. I'm closing this for now since not sure what can be done on your end.
